# Generated by Django 2.0.5 on 2018-05-29 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_id', models.CharField(max_length=16, unique=True, verbose_name='Amazon ID')),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('endpoint', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='marketplace',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djmws.Region'),
        ),
    ]
