# Generated by Django 2.0.3 on 2018-03-19 16:47

from django.db import migrations


def forwards(apps, schema_editor):
    Region = apps.get_model('djmws', 'Region')
    EU = Region(code='EU', endpoint='https://mws-eu.amazonservices.com')
    EU.save()
    NA = Region(code='NA', endpoint='https://mws.amazonservices.com')
    NA.save()
    Marketplace = apps.get_model('djmws', 'Marketplace')
    for (code, amazon_id) in {
        ('UK', 'A1F83G8C2ARO7P'),
        ('FR','A13V1IB3VIYZZH'),
        ('DE', 'A1PA6795UKMFR9'),
        ('IT', 'APJ6JRA9NG5V4'),
        ('ES', 'A1RKKUPIHCS9HS'),
    }:
        Marketplace(
            amazon_id=amazon_id,
            region=EU,
            code=code,
        ).save()
    for (code, amazon_id) in {
        ('US', 'ATVPDKIKX0DER'),
        ('CA', 'A2EUQ1WTGCTBG2'),
        ('MX', 'A1AM78C64UM0Y8'),
    }:
        Marketplace(
            amazon_id=amazon_id,
            region=NA,
            code=code,
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('djmws', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
