# Generated by Django 2.0.5 on 2018-05-29 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djmws', '0002_populate_regions_marketplaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='MWSCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=32, verbose_name='Seller ID')),
                ('access_key', models.CharField(max_length=32)),
                ('secret_key', models.CharField(max_length=64)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djmws.Region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mws_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MWS Credentials',
                'verbose_name_plural': 'MWS Credentials',
            },
        ),
        migrations.AlterUniqueTogether(
            name='mwscredentials',
            unique_together={('user', 'region')},
        ),
    ]
